services:
  nginx:
    image: nginx
    container_name: nginx-auth
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  auth-server:
    build: ./
    container_name: auth-server
    environment:
      - AUTH_PASSWORD=test
      - AUTH_TOKEN_SECRET=verysecret
